apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-web-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-web-service
  template:
    metadata:
      name: java-web-service
      labels:
        app: java-web-service
    spec:
      containers:
      - name: java-web-service
        image: docker.io/nagabhushanam/java-web-service:latest
