pipeline {
    
    agent any


    environment {
        SONAR_HOST_URL = "http://74.225.237.22:9000/"
        SONAR_PROJECT_KEY = 'transfer-service'
        SONAR_TOKEN = credentials('sonar-token')
        MAVEN_OPTS = "-Dmaven.repo.local=.m2/repository" // Maven caching
    }

    options {
        timestamps()                     // Adds timestamps to console output
        skipStagesAfterUnstable()       // Skips remaining stages if a stage is marked unstable
    }

    stages {

        stage("📦 Compile") {
            steps {
                script {
                    def serviceDir = "java-web-service"
                    dir(serviceDir) {
                        sh './mvnw compile'
                    }
                }
            }
        }
        stage("🧪 Unit Test + Code Coverage") {
            steps {
                script {
                    def serviceDir = "java-web-service"
                    dir(serviceDir) {
                        sh './mvnw test jacoco:report'
                    }
                }
            }
            post {
                always {
                    script {
                        def reportPath = "java-web-service/target/surefire-reports"
                        if (fileExists(reportPath)) {
                            junit "${reportPath}/*.xml"
                        } else {
                            echo "❗ No test reports found."
                        }
                        // Publish Jacoco code coverage
                        jacoco execPattern: '**/target/jacoco.exec'
                    }
                }
            }
        }

    }

}